name: Python package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.7.1, 3.8, 3.9, 3.10]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install flake8
        pip install mypy
        pip install -e .

    - name: Lint with flake8
      run: |
        flake8 mindflow tests

    - name: Type check with mypy
      run: |
        mypy mindflow

    - name: Test with pytest
      run: |
        pytest --junitxml=junit/test-results.xml tests

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: Test results
        path: junit/test-results.xml